<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class Alcateia_Delivery_Admin {
	public function hooks(){ add_action('admin_menu',array($this,'menu')); add_action('admin_enqueue_scripts',array($this,'enqueue')); add_action('admin_post_alcateia_delivery_import',array($this,'import')); add_action('admin_post_alcateia_delivery_export',array($this,'export')); add_action('admin_post_alcateia_delivery_restore',array($this,'restore')); add_action('admin_post_alcateia_delivery_license',array($this,'license')); add_action('admin_post_alcateia_delivery_maintenance',array($this,'maintenance')); add_action('wp_ajax_alcateia_delivery_grid',array($this,'ajax_grid')); add_action('wp_ajax_alcateia_delivery_health',array($this,'ajax_health')); }
	public function menu(){ add_submenu_page('woocommerce','Alcateia Delivery','Alcateia Delivery','manage_woocommerce','alcateia-delivery',array($this,'render')); }
	public function enqueue($hook){ if('woocommerce_page_alcateia-delivery'!==$hook)return; wp_enqueue_style('alcateia-design-system',ALCATEIA_DELIVERY_URL.'assets/css/admin-design-system.css',array(),ALCATEIA_DELIVERY_VERSION); wp_enqueue_style('alcateia-dashboard',ALCATEIA_DELIVERY_URL.'assets/css/admin-dashboard.css',array('alcateia-design-system'),ALCATEIA_DELIVERY_VERSION); wp_enqueue_style('alcateia-grid',ALCATEIA_DELIVERY_URL.'assets/css/admin-grid.css',array('alcateia-design-system'),ALCATEIA_DELIVERY_VERSION); wp_enqueue_script('alcateia-admin-dashboard',ALCATEIA_DELIVERY_URL.'assets/js/admin-dashboard.js',array('jquery'),ALCATEIA_DELIVERY_VERSION,true); wp_enqueue_script('alcateia-admin-grid',ALCATEIA_DELIVERY_URL.'assets/js/admin-grid.js',array('jquery'),ALCATEIA_DELIVERY_VERSION,true); wp_enqueue_script('alcateia-admin-importer',ALCATEIA_DELIVERY_URL.'assets/js/admin-importer.js',array('jquery'),ALCATEIA_DELIVERY_VERSION,true); wp_enqueue_script('alcateia-admin-health',ALCATEIA_DELIVERY_URL.'assets/js/admin-health.js',array('jquery'),ALCATEIA_DELIVERY_VERSION,true); wp_localize_script('alcateia-admin-dashboard','alcateiaAdmin',array('ajaxUrl'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('alcateia_admin'),'i18nLoading'=>esc_html__('Carregando insights...', 'alcateia-delivery'))); }
	public function render(){ global $wpdb; $t=Alcateia_Delivery_DB::table_name(); $total=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$t}"); $active=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$t} WHERE active=1"); $last=$wpdb->get_var("SELECT MAX(updated_at) FROM {$t}"); $sim=(int)get_option('alcateia_delivery_sim_total',0); $health=Alcateia_Delivery_Observability::health_report(); require ALCATEIA_DELIVERY_PATH.'includes/views-admin.php'; }
	public function ajax_grid(){ check_ajax_referer('alcateia_admin','nonce'); if(!current_user_can('manage_woocommerce'))wp_send_json_error(array('message'=>esc_html__('Permissão negada.','alcateia-delivery')),403); global $wpdb; $t=Alcateia_Delivery_DB::table_name(); $q=sanitize_text_field(wp_unslash($_GET['q']??'')); $where=''; $args=array(); if($q){$where=' WHERE region LIKE %s OR region_label LIKE %s'; $like='%'.$wpdb->esc_like($q).'%'; $args=array($like,$like);} $sql="SELECT id,priority,region,region_label,weight_from,weight_to,qty_from,qty_to,shipping_cost,active,updated_at FROM {$t}{$where} ORDER BY priority ASC, id DESC LIMIT 150"; if($args){$sql=$wpdb->prepare($sql,$args);} $rows=$wpdb->get_results($sql,ARRAY_A); wp_send_json_success($rows); }
	public function ajax_health(){ check_ajax_referer('alcateia_admin','nonce'); if(!current_user_can('manage_woocommerce'))wp_send_json_error(array('message'=>esc_html__('Permissão negada.','alcateia-delivery')),403); wp_send_json_success(Alcateia_Delivery_Observability::health_report()); }
	public function import(){ check_admin_referer('alcateia_delivery_import'); if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Permissão negada.','alcateia-delivery')); if(get_transient('alcateia_delivery_import_lock'))wp_die(esc_html__('Importação em andamento. Tente novamente em alguns segundos.','alcateia-delivery')); set_transient('alcateia_delivery_import_lock',1,60); if(empty($_FILES['rates_file']['tmp_name']))wp_die(esc_html__('Arquivo ausente.','alcateia-delivery')); $file=$_FILES['rates_file']; $finfo=wp_check_filetype_and_ext($file['tmp_name'],$file['name']); if(!in_array($finfo['ext'],array('csv','xlsx'),true))wp_die(esc_html__('Formato inválido.','alcateia-delivery')); $res='csv'===$finfo['ext']?Alcateia_Delivery_Importer::import_csv($file['tmp_name'],false):Alcateia_Delivery_Importer::import_xlsx($file['tmp_name'],false); delete_transient('alcateia_delivery_import_lock'); update_option('alcateia_delivery_last_import',gmdate('c'),false); wp_safe_redirect(admin_url('admin.php?page=alcateia-delivery&imported='.(is_wp_error($res)?0:1))); exit; }
	public function export(){ check_admin_referer('alcateia_delivery_export'); if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Permissão negada.','alcateia-delivery')); global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.Alcateia_Delivery_DB::table_name(),ARRAY_A); header('Content-Type:text/csv'); header('Content-Disposition: attachment; filename=alcateia-rates.csv'); $o=fopen('php://output','w'); if($rows){fputcsv($o,array_keys($rows[0])); foreach($rows as $r)fputcsv($o,$r);} fclose($o); exit; }
	public function restore(){ check_admin_referer('alcateia_delivery_restore'); if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Permissão negada.','alcateia-delivery')); Alcateia_Delivery_Importer::import_default_csv(); Alcateia_Delivery_Plugin::flush_cache(); wp_safe_redirect(admin_url('admin.php?page=alcateia-delivery&restored=1')); exit; }
	public function license(){ check_admin_referer('alcateia_delivery_license'); if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Permissão negada.','alcateia-delivery')); $action=sanitize_text_field(wp_unslash($_POST['license_action']??'')); if('activate'===$action){Alcateia_Delivery_License_Manager::activate(sanitize_text_field(wp_unslash($_POST['license_key']??'')));}else{Alcateia_Delivery_License_Manager::deactivate();} wp_safe_redirect(admin_url('admin.php?page=alcateia-delivery')); exit; }
	public function maintenance(){ check_admin_referer('alcateia_delivery_maintenance'); if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Permissão negada.','alcateia-delivery')); update_option('alcateia_delivery_maintenance_mode', !empty($_POST['enabled'])?'yes':'no', false); wp_safe_redirect(admin_url('admin.php?page=alcateia-delivery')); exit; }
}
