<?php $license = Alcateia_Delivery_License_Manager::get_status(); $deadline_settings = Alcateia_Delivery_Deadline::get_settings(); $delivery_settings = array( 'default_days' => $deadline_settings['base_days'], 'extra_days' => $deadline_settings['extra_days'] ); ?>
<div class="wrap alcateia-delivery-admin">
  <div class="ad-mesh"></div>
  <header class="ad-topbar"><div><p class="ad-breadcrumb"><?php echo esc_html__('WooCommerce / Alcateia Delivery','alcateia-delivery'); ?></p><h1><?php echo esc_html__('Alcateia Delivery — Control Center','alcateia-delivery'); ?></h1><p><?php echo esc_html__('Sua operação de frete está saudável e pronta para escala.','alcateia-delivery'); ?></p></div><span class="ad-badge success"><?php echo esc_html__('Entrega Express Online','alcateia-delivery'); ?></span></header>
  <section class="ad-kpis" aria-label="KPIs">
    <article class="ad-card"><h3><?php echo esc_html__('Total de regras','alcateia-delivery'); ?></h3><p><?php echo esc_html($total); ?></p></article>
    <article class="ad-card"><h3><?php echo esc_html__('Regras ativas','alcateia-delivery'); ?></h3><p><?php echo esc_html($active); ?></p></article>
    <article class="ad-card"><h3><?php echo esc_html__('Simulações','alcateia-delivery'); ?></h3><p><?php echo esc_html($sim); ?></p></article>
    <article class="ad-card"><h3><?php echo esc_html__('Última atualização','alcateia-delivery'); ?></h3><p><?php echo esc_html($last); ?></p></article>
  </section>
  <section class="ad-layout">
    <aside class="ad-sidebar ad-glass"><h3><?php echo esc_html__('Ações rápidas','alcateia-delivery'); ?></h3><button class="button button-primary" id="alcateia-refresh-grid"><?php echo esc_html__('Atualizar Data Grid','alcateia-delivery'); ?></button><button class="button" id="ad-open-import"><?php echo esc_html__('Importação Premium','alcateia-delivery'); ?></button><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('alcateia_delivery_maintenance'); ?><input type="hidden" name="action" value="alcateia_delivery_maintenance"/><label><input type="checkbox" name="enabled" value="1" <?php checked(get_option('alcateia_delivery_maintenance_mode','no'),'yes'); ?> /> <?php echo esc_html__('Modo manutenção','alcateia-delivery'); ?></label><button class="button"><?php echo esc_html__('Salvar','alcateia-delivery'); ?></button></form></aside>
    <main>
      <section class="ad-glass ad-panel"><h2><?php echo esc_html__('Health Center','alcateia-delivery'); ?></h2><div id="ad-health-grid" class="ad-health-grid" data-score="100"></div><p class="ad-microcopy"><?php echo esc_html__('Nenhuma falha crítica detectada nas últimas simulações.','alcateia-delivery'); ?></p></section>
      <section class="ad-glass ad-panel"><h2><?php echo esc_html__('Analytics','alcateia-delivery'); ?></h2><canvas id="ad-chart-sim" height="100" aria-label="Simulações" role="img"></canvas><div class="ad-skeleton" id="ad-chart-skeleton"></div></section>

      <section class="ad-glass ad-panel"><h2><?php echo esc_html__('Prazos de entrega','alcateia-delivery'); ?></h2><p><?php echo esc_html__('Configure o prazo padrão e a quantidade de dias extras aplicada às cotações.','alcateia-delivery'); ?></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('alcateia_delivery_settings'); ?><input type="hidden" name="action" value="alcateia_delivery_settings"/><label><?php echo esc_html__('Prazo padrão (dias úteis)','alcateia-delivery'); ?><input type="number" min="1" step="1" name="default_days" value="<?php echo esc_attr((int)$delivery_settings['default_days']); ?>"/></label><label><?php echo esc_html__('Dias extras','alcateia-delivery'); ?><input type="number" min="0" step="1" name="extra_days" value="<?php echo esc_attr((int)$delivery_settings['extra_days']); ?>"/></label><button class="button button-primary"><?php echo esc_html__('Salvar prazos','alcateia-delivery'); ?></button></form></section>
      <section class="ad-glass ad-panel"><h2><?php echo esc_html__('Tabela de Regras Premium','alcateia-delivery'); ?></h2><input id="ad-grid-search" type="search" placeholder="<?php echo esc_attr__('Buscar por região, rótulo ou regra','alcateia-delivery'); ?>" aria-label="<?php echo esc_attr__('Buscar regras','alcateia-delivery'); ?>"><div id="alcateia-grid" class="ad-grid-wrap"><div class="ad-empty"><?php echo esc_html__('Carregando regras...','alcateia-delivery'); ?></div></div></section>
      <section class="ad-glass ad-panel"><h2><?php echo esc_html__('Licenciamento','alcateia-delivery'); ?></h2><p><?php echo esc_html__('Status atual:','alcateia-delivery'); ?> <span class="ad-badge"><?php echo esc_html($license['status']); ?></span></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('alcateia_delivery_license'); ?><input type="hidden" name="action" value="alcateia_delivery_license"/><input type="text" name="license_key" placeholder="<?php echo esc_attr__('Cole sua chave de licença','alcateia-delivery'); ?>"/><button class="button button-primary" name="license_action" value="activate"><?php echo esc_html__('Ativar','alcateia-delivery'); ?></button><button class="button" name="license_action" value="deactivate"><?php echo esc_html__('Desativar','alcateia-delivery'); ?></button></form></section>
    </main>
  </section>
  <div class="ad-modal" id="ad-import-modal" hidden><div class="ad-modal-content ad-glass"><h3><?php echo esc_html__('Importação Inteligente','alcateia-delivery'); ?></h3><p><?php echo esc_html__('A tabela será validada antes da publicação.','alcateia-delivery'); ?></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" enctype="multipart/form-data"><?php wp_nonce_field('alcateia_delivery_import'); ?><input type="hidden" name="action" value="alcateia_delivery_import"/><label class="ad-dropzone"><input type="file" name="rates_file" required/><span><?php echo esc_html__('Arraste CSV/XLSX ou clique para selecionar','alcateia-delivery'); ?></span></label><progress id="ad-import-progress" max="100" value="0"></progress><button class="button button-primary"><?php echo esc_html__('Validar e Importar','alcateia-delivery'); ?></button><button type="button" class="button" id="ad-close-import"><?php echo esc_html__('Cancelar','alcateia-delivery'); ?></button></form></div></div>
</div>
