<?php
if (!defined('ABSPATH')) { exit; }
class PSI_AI_Batch_Runner {
    private $plugin;
    private $rollout_limits = array('test'=>500, 'small'=>2000, 'medium'=>10000, 'advanced'=>0, 'total'=>0);
    public function __construct($plugin) { $this->plugin = $plugin; }
    public function import_sitemaps() { global $wpdb; $settings=get_option('psi_ai_settings', PSI_AI_Plugin::default_settings()); $urls=$this->plugin->sitemap_reader->read_all($settings['sitemaps']); foreach($urls as $url){ $wpdb->query($wpdb->prepare("INSERT INTO {$wpdb->prefix}psi_ai_pages (url,status,updated_at) SELECT %s,'pending',%s WHERE NOT EXISTS (SELECT 1 FROM {$wpdb->prefix}psi_ai_pages WHERE url=%s)", $url, current_time('mysql'), $url)); } return count($urls); }
    public function schedule() { if (!wp_next_scheduled('psi_ai_process_batch')) wp_schedule_event(time()+60, 'hourly', 'psi_ai_process_batch'); }
    public function process_scheduled_batch() { $this->process_batch(false); }
    public function enqueue_batch($dry_run = true, $limit = null, $rollout_mode = 'manual') { $settings=get_option('psi_ai_settings', PSI_AI_Plugin::default_settings()); $limit = $limit ? absint($limit) : absint($settings['batch_size']); return $this->plugin->resilient_runner->enqueue(array('dry_run'=>(bool)$dry_run,'limit'=>$limit,'rollout_mode'=>sanitize_key($rollout_mode))); }
    public function process_next($dry_run = true, $rollout_mode = 'manual') { global $wpdb; $row=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}psi_ai_pages WHERE status IN ('pending','error','queued') ORDER BY id ASC LIMIT 1"); if (!$row) return array('processed'=>0,'status'=>'empty'); $wpdb->update($wpdb->prefix.'psi_ai_pages', array('status'=>'running','updated_at'=>current_time('mysql')), array('id'=>$row->id)); $settings=get_option('psi_ai_settings', PSI_AI_Plugin::default_settings()); $result=$this->process_row($row,(bool)$dry_run,$settings); $result['processed']=1; return $result; }
    public function process_batch($dry_run = null, $limit = null, $rollout_mode = 'manual') { global $wpdb; $settings=get_option('psi_ai_settings', PSI_AI_Plugin::default_settings()); if ($dry_run===null) $dry_run=(bool)$settings['dry_run']; $limit = $limit ? absint($limit) : absint($settings['batch_size']); $rollout_id = $this->start_rollout($rollout_mode, $limit); $rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}psi_ai_pages WHERE status IN ('pending','error') ORDER BY id ASC LIMIT %d", $limit)); $stats=array('processed'=>0,'published'=>0,'blocked'=>0,'review'=>0,'quality'=>array()); foreach($rows as $row){ $result=$this->process_row($row,$dry_run,$settings); $stats['processed']++; $stats['quality'][]=$result['quality'] ?? 0; if (($result['status'] ?? '')==='updated') $stats['published']++; if (in_array(($result['status'] ?? ''), array('manual_review','blocked','recommend_noindex'), true)) $stats['blocked']++; if (($result['status'] ?? '')==='manual_review') $stats['review']++; } $this->finish_rollout($rollout_id,$stats); return count($rows); }
    public function process_rollout($mode, $custom_limit = 0, $double_confirm = false, $dry_run = true) { $mode=sanitize_key($mode); if ($mode==='total' && !$double_confirm) return new WP_Error('confirm_required','O lote total exige confirmação manual dupla.'); $limit = $this->rollout_limits[$mode] ?? 0; if ($mode==='advanced') $limit=absint($custom_limit); if ($mode==='total') $limit=999999; return $this->process_batch($dry_run, $limit, $mode); }
    private function process_row($row,$dry_run,$settings) { global $wpdb; $detected=$this->plugin->detector->detect_by_url($row->url); if (is_wp_error($detected)) { $wpdb->update($wpdb->prefix.'psi_ai_pages', array('status'=>$detected->get_error_code(),'flags'=>$detected->get_error_message(),'updated_at'=>current_time('mysql')), array('id'=>$row->id)); return array('status'=>$detected->get_error_code()); } $generated=$this->plugin->generator->generate($detected); $block=$this->plugin->boldbuilder->wrap($generated['html'],$detected['uses_boldbuilder']); $similarity=$this->plugin->similarity_guard->evaluate($detected['post_id'],$block,$generated['entities']); if ($similarity['action']==='regenerate') { $generated=$this->plugin->generator->generate($detected, 2); $block=$this->plugin->boldbuilder->wrap($generated['html'],$detected['uses_boldbuilder']); $similarity=$this->plugin->similarity_guard->evaluate($detected['post_id'],$block,$generated['entities']); $this->plugin->logger->log('warning','Variação regenerada por similaridade', array('post_id'=>$detected['post_id'],'similarity'=>$similarity,'visual'=>$generated['visual'])); } $quality=$this->plugin->scorer->score($block); if (!empty($generated['visual']['warnings'])) { $quality['flags'][] = 'revisao_visual_obrigatoria'; } $status = $quality['score'] < (float)$settings['quality_threshold'] ? 'manual_review' : ($dry_run ? 'simulated' : 'updated'); if ($similarity['action']==='block') $status='manual_review'; if (!empty($generated['visual']['warnings'])) $status='visual_review'; if ($similarity['action']==='recommend_noindex') $status='recommend_noindex'; if (!$dry_run && $status==='updated') { $this->plugin->backup->create($detected['post_id']); $clean=$this->plugin->cleaner->remove_old($detected['post']->post_content); $new=$this->plugin->cleaner->insert_after_budget($clean,$block); $allowed = array_merge(wp_kses_allowed_html('post'), $this->plugin->generator->allowed_svg()); wp_update_post(array('ID'=>$detected['post_id'],'post_content'=>wp_kses($new, $allowed)));  $this->create_validation_plan($detected['post_id'], $row->url); } if (in_array($status, array('manual_review','recommend_noindex','visual_review'), true)) { $this->plugin->logger->log('warning','Página bloqueada para revisão por qualidade/similaridade', array('post_id'=>$detected['post_id'],'status'=>$status,'quality'=>$quality,'similarity'=>$similarity,'visual'=>$generated['visual'])); } $flags=array_merge($quality['flags'], array('similarity_'.$similarity['similarity'], 'source_'.$similarity['source'])); $wpdb->update($wpdb->prefix.'psi_ai_pages', array('post_id'=>$detected['post_id'],'status'=>$status,'quality_score'=>$quality['score'],'flags'=>implode(',',$flags),'data'=>wp_json_encode(array('detected'=>$detected,'entities'=>$generated['entities'],'similarity'=>$similarity,'visual'=>$generated['visual'])),'updated_at'=>current_time('mysql')), array('id'=>$row->id)); return array('status'=>$status,'quality'=>$quality['score']); }
    private function create_validation_plan($post_id, $url) { global $wpdb; $changed=current_time('mysql'); $now=current_time('timestamp'); $wpdb->insert($wpdb->prefix.'psi_ai_validation_plan', array('post_id'=>$post_id,'url'=>$url,'changed_at'=>$changed,'status_before'=>'Rastreada, mas não indexada no momento','status_after'=>'Aguardando reavaliação','inspect_at'=>date('Y-m-d', strtotime('+10 days',$now)),'request_indexing_at'=>date('Y-m-d', strtotime('+15 days',$now)),'review_at'=>date('Y-m-d', strtotime('+30 days',$now))), array('%d','%s','%s','%s','%s','%s','%s','%s')); }
    private function start_rollout($mode, $limit) { global $wpdb; $wpdb->insert($wpdb->prefix.'psi_ai_rollouts', array('mode'=>sanitize_key($mode),'started_at'=>current_time('mysql'),'target_count'=>absint($limit),'status'=>'running'), array('%s','%s','%d','%s')); return $wpdb->insert_id; }
    private function finish_rollout($id,$stats) { global $wpdb; $avg = count($stats['quality']) ? array_sum($stats['quality']) / count($stats['quality']) : 0; $wpdb->update($wpdb->prefix.'psi_ai_rollouts', array('finished_at'=>current_time('mysql'),'processed_count'=>$stats['processed'],'published_count'=>$stats['published'],'blocked_count'=>$stats['blocked'],'review_count'=>$stats['review'],'average_quality'=>$avg,'status'=>'finished'), array('id'=>$id)); }
}
